version: "3"
services:
  nginx:
    image: nginx:1.20.1-alpine
    environment:
      - VIRTUAL_HOST=localhost
    depends_on:
      - php-fpm
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./html/:/var/www/html/
    restart: on-failure
    networks:
      - frontend
      - backend
  php-fpm:
    build:
      context: ./php
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./html/:/var/www/html/
    restart: on-failure
    networks:
      - backend
  mysql:
    image: mysql:latest
    volumes:
      - ../mysql-data/db:/var/lib/mysql
    restart: on-failure 
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
    networks:
      - backend
networks:
  frontend:
    external:
      name: proxy_proxy
  backend:
    
